// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod sftpx {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod protocol {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum ChunkPacketOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ChunkPacket<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ChunkPacket<'a> {
  type Inner = ChunkPacket<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> ChunkPacket<'a> {
  pub const VT_CHUNK_ID: flatbuffers::VOffsetT = 4;
  pub const VT_BYTE_OFFSET: flatbuffers::VOffsetT = 6;
  pub const VT_CHUNK_LENGTH: flatbuffers::VOffsetT = 8;
  pub const VT_CHECKSUM: flatbuffers::VOffsetT = 10;
  pub const VT_END_OF_FILE: flatbuffers::VOffsetT = 12;
  pub const VT_DATA: flatbuffers::VOffsetT = 14;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ChunkPacket { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args ChunkPacketArgs<'args>
  ) -> flatbuffers::WIPOffset<ChunkPacket<'bldr>> {
    let mut builder = ChunkPacketBuilder::new(_fbb);
    builder.add_byte_offset(args.byte_offset);
    builder.add_chunk_id(args.chunk_id);
    if let Some(x) = args.data { builder.add_data(x); }
    if let Some(x) = args.checksum { builder.add_checksum(x); }
    builder.add_chunk_length(args.chunk_length);
    builder.add_end_of_file(args.end_of_file);
    builder.finish()
  }


  #[inline]
  pub fn chunk_id(&self) -> u64 {
    self._tab.get::<u64>(ChunkPacket::VT_CHUNK_ID, Some(0)).unwrap()
  }
  #[inline]
  pub fn byte_offset(&self) -> u64 {
    self._tab.get::<u64>(ChunkPacket::VT_BYTE_OFFSET, Some(0)).unwrap()
  }
  #[inline]
  pub fn chunk_length(&self) -> u32 {
    self._tab.get::<u32>(ChunkPacket::VT_CHUNK_LENGTH, Some(0)).unwrap()
  }
  #[inline]
  pub fn checksum(&self) -> Option<&'a [u8]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(ChunkPacket::VT_CHECKSUM, None).map(|v| v.safe_slice())
  }
  #[inline]
  pub fn end_of_file(&self) -> bool {
    self._tab.get::<bool>(ChunkPacket::VT_END_OF_FILE, Some(false)).unwrap()
  }
  #[inline]
  pub fn data(&self) -> Option<&'a [u8]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(ChunkPacket::VT_DATA, None).map(|v| v.safe_slice())
  }
}

impl flatbuffers::Verifiable for ChunkPacket<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("chunk_id", Self::VT_CHUNK_ID, false)?
     .visit_field::<u64>("byte_offset", Self::VT_BYTE_OFFSET, false)?
     .visit_field::<u32>("chunk_length", Self::VT_CHUNK_LENGTH, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("checksum", Self::VT_CHECKSUM, false)?
     .visit_field::<bool>("end_of_file", Self::VT_END_OF_FILE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("data", Self::VT_DATA, false)?
     .finish();
    Ok(())
  }
}
pub struct ChunkPacketArgs<'a> {
    pub chunk_id: u64,
    pub byte_offset: u64,
    pub chunk_length: u32,
    pub checksum: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub end_of_file: bool,
    pub data: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for ChunkPacketArgs<'a> {
  #[inline]
  fn default() -> Self {
    ChunkPacketArgs {
      chunk_id: 0,
      byte_offset: 0,
      chunk_length: 0,
      checksum: None,
      end_of_file: false,
      data: None,
    }
  }
}

pub struct ChunkPacketBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ChunkPacketBuilder<'a, 'b> {
  #[inline]
  pub fn add_chunk_id(&mut self, chunk_id: u64) {
    self.fbb_.push_slot::<u64>(ChunkPacket::VT_CHUNK_ID, chunk_id, 0);
  }
  #[inline]
  pub fn add_byte_offset(&mut self, byte_offset: u64) {
    self.fbb_.push_slot::<u64>(ChunkPacket::VT_BYTE_OFFSET, byte_offset, 0);
  }
  #[inline]
  pub fn add_chunk_length(&mut self, chunk_length: u32) {
    self.fbb_.push_slot::<u32>(ChunkPacket::VT_CHUNK_LENGTH, chunk_length, 0);
  }
  #[inline]
  pub fn add_checksum(&mut self, checksum: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ChunkPacket::VT_CHECKSUM, checksum);
  }
  #[inline]
  pub fn add_end_of_file(&mut self, end_of_file: bool) {
    self.fbb_.push_slot::<bool>(ChunkPacket::VT_END_OF_FILE, end_of_file, false);
  }
  #[inline]
  pub fn add_data(&mut self, data: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ChunkPacket::VT_DATA, data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ChunkPacketBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ChunkPacketBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ChunkPacket<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ChunkPacket<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ChunkPacket");
      ds.field("chunk_id", &self.chunk_id());
      ds.field("byte_offset", &self.byte_offset());
      ds.field("chunk_length", &self.chunk_length());
      ds.field("checksum", &self.checksum());
      ds.field("end_of_file", &self.end_of_file());
      ds.field("data", &self.data());
      ds.finish()
  }
}
#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_root_as_chunk_packet<'a>(buf: &'a [u8]) -> ChunkPacket<'a> {
  unsafe { flatbuffers::root_unchecked::<ChunkPacket<'a>>(buf) }
}

#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_size_prefixed_root_as_chunk_packet<'a>(buf: &'a [u8]) -> ChunkPacket<'a> {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<ChunkPacket<'a>>(buf) }
}

#[inline]
/// Verifies that a buffer of bytes contains a `ChunkPacket`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_chunk_packet_unchecked`.
pub fn root_as_chunk_packet(buf: &[u8]) -> Result<ChunkPacket, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<ChunkPacket>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `ChunkPacket` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_chunk_packet_unchecked`.
pub fn size_prefixed_root_as_chunk_packet(buf: &[u8]) -> Result<ChunkPacket, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<ChunkPacket>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `ChunkPacket` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_chunk_packet_unchecked`.
pub fn root_as_chunk_packet_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ChunkPacket<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<ChunkPacket<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `ChunkPacket` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_chunk_packet_unchecked`.
pub fn size_prefixed_root_as_chunk_packet_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ChunkPacket<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<ChunkPacket<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a ChunkPacket and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `ChunkPacket`.
pub unsafe fn root_as_chunk_packet_unchecked(buf: &[u8]) -> ChunkPacket {
  flatbuffers::root_unchecked::<ChunkPacket>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed ChunkPacket and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `ChunkPacket`.
pub unsafe fn size_prefixed_root_as_chunk_packet_unchecked(buf: &[u8]) -> ChunkPacket {
  flatbuffers::size_prefixed_root_unchecked::<ChunkPacket>(buf)
}
#[inline]
pub fn finish_chunk_packet_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<ChunkPacket<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_chunk_packet_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<ChunkPacket<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod protocol
}  // pub mod sftpx

