// This file is @generated by prost-build.
/// Chunk packet containing data and metadata for a single file chunk
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChunkPacket {
    /// Unique chunk identifier (chunk number, starting from 0)
    #[prost(uint64, tag = "1")]
    pub chunk_id: u64,
    /// Byte offset where this chunk starts in the file
    #[prost(uint64, tag = "2")]
    pub byte_offset: u64,
    /// Length of the chunk data in bytes
    #[prost(uint32, tag = "3")]
    pub chunk_length: u32,
    /// Checksum of the chunk data (BLAKE3 hash)
    #[prost(bytes = "vec", tag = "4")]
    pub checksum: ::prost::alloc::vec::Vec<u8>,
    /// Flag indicating this is the last chunk of the file
    #[prost(bool, tag = "5")]
    pub end_of_file: bool,
    /// The actual chunk data payload
    #[prost(bytes = "vec", tag = "6")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
